// ============================================================================
// Stage B — Link LandCluster zones to res-8 ZoneCells derived from site coords
//
// A LandCluster's spatial footprint is the union of res-8 backbone cells
// containing its constituent monitoring sites. This stage reads the H3 CSV
// generated by generate-land-cluster-h3.mjs and links each backbone cell
// to the cluster via IN_ZONE, then attaches to Moku via WITHIN.
//
// Unlike IAL (which polyfills legal boundaries), LandCluster coverage is
// bottom-up: derived from where observations actually happen.
//
// Prerequisites:
//   - LandCluster Zone nodes created (Stage A)
//   - Moku ZoneCells loaded (Stage 0, moku/)
// ============================================================================

LOAD CSV WITH HEADERS FROM 'https://raw.githubusercontent.com/joehagedorn/neo4j/main/land-cluster/LandCluster_Zones_H3.csv' AS row

WITH row,
     trim(row.cluster_id)     AS cluster_id,
     row.h3_cell               AS h3,
     toInteger(row.resolution) AS res,
     toLower(row.moku_id)      AS moku_id,
     trim(row.version)         AS version,
     row.data_source           AS data_source

// 1) Match existing backbone ZoneCell (do NOT create new cells)
MATCH (zc:ZoneCell {h3_cell: h3})

// 2) Link ZoneCell to LandCluster via IN_ZONE
WITH zc, cluster_id, moku_id, version, data_source
MATCH (z:Zone:LandCluster {id: cluster_id})
SET z.version     = coalesce(version, z.version),
    z.updated_at  = datetime()
MERGE (zc)-[:IN_ZONE]->(z)

// 3) Ensure ZoneCell is attached to Moku (should already exist from backbone)
WITH zc, moku_id
WHERE moku_id IS NOT NULL AND moku_id <> ""
MATCH (m:Moku {id: moku_id})
MERGE (zc)-[:WITHIN]->(m);
